title:            Cross-Platform-Blog.de
description:      Node.js, Electron, Cordova and JavaScript

# put your disqus here
disqus_shortname: cross-platform-blog-com
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://www.cross-platform-blog.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Kategorien'
    url: '/categories'
    type: 'categories'
  - title: 'Feed'
    url: '/feed.xml'
  #- title: 'Favorites'
  #  url: '#'
  #  submenu:
  #    - title: 'Code Highlighter'
  #      url: '/intro/code-highlighting-post/'
  #    - title: 'Sample Post'
  #      url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Gregor Biswanger
  site:           https://about.me/gregor.biswanger
  avatar:         images/Gregor_Biswanger.jpg
  bio:            "Gregor Biswanger (Microsoft MVP, Intel Black Belt & Intel Software Innovator) ist freier Dozent, Berater, Trainer, Autor und Sprecher. Er berät große und mittelständische Unternehmen, Organisationen und Agenturen rund um die Themen zur Softwarearchitektur, Web- und Cross-Platform-Entwicklung. Außerdem schreibt er online als freier Autor für heise-developer und bringt für Fachmagazine auch gerne Artikel aufs Blatt. Er ist international als Sprecher auf zahlreichen Konferenzen und Communities unterwegs."
  email:          gregor.biswanger@web-enliven.de
  # Twitter nick for use in Twitter cards and follow button.
  twitter: BFreakout # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: GregorBiswanger
  facebook: gregor.biswanger
  google: 110276867823986080798

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: BFreakout

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "facebook"
    url: "https://www.facebook.com/gregor.biswanger"
  - title: "twitter"
    url: "https://www.twitter.com/BFreakout"  
  - title: "github"
    url: "https://github.com/GregorBiswanger"
  - title: "linkedin"
    url: "http://www.linkedin.com/pub/gregor-biswanger/11/420/513"
  - title: "youtube"
    url: "https://www.youtube.com/user/bfreakout"
  - title: "google"
    url: "http://plus.google.com/110276867823986080798/"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-89852203-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
locale:      de_DE
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
share: true
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]
theme: neo-hpstr-jekyll-theme
